apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-cc-webclient
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
---

apiVersion: v1                                  # Api k8s
kind: PersistentVolume
metadata:
  name: pv-cc-webclient
spec:
  capacity:
   storage: 1Gi
  volumeMode: Filesystem
  accessModes:
   - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
   path: /tmp/demo
   server: 172.31.10.22
---
apiVersion: v1                                  # Api k8s
kind: PersistentVolumeClaim
metadata:
  name: pvc-cc-webclient 
spec:
  volumeName: pv-cc-webclient
  accessModes:
   - ReadWriteMany
  resources:
   requests:
    storage: 1Gi