apiVersion: v1
kind: Service
metadata:  
  labels:
    app: ccapi-#ORG#-#DOMAIN-FOR-LABEL#
  name: ccapi-#ORG#-#DOMAIN-FOR-LABEL#
  namespace: hlpesproject-net
spec:
  ports:
  - nodePort: 32081
    port: PORT#
    protocol: TCP
    targetPort: PORT#
  selector:
    app: ccapi-#ORG#-#DOMAIN-FOR-LABEL#
  sessionAffinity: ClientIP
  type: LoadBalancer
 # externalIPs:    #only k8s, if not get automatic external-ip
 # - 0.0.0.0  
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name:  ccapi-#ORG#-#DOMAIN-FOR-LABEL#
  namespace: hlpesproject-net  
  labels:
    app:  ccapi-#ORG#-#DOMAIN-FOR-LABEL#
spec:
  selector:   
      app: ccapi-#ORG#-#DOMAIN-FOR-LABEL#
      deploymentconfig: ccapi-#ORG#-#DOMAIN-FOR-LABEL#
  replicas: 1  
  template:
    metadata:
      labels:
        app:  ccapi-#ORG#-#DOMAIN-FOR-LABEL#
        deploymentconfig: ccapi-#ORG#-#DOMAIN-FOR-LABEL#
    spec:
      hostAliases:
      - ip: 18.207.45.66
        hostnames:
        - peer0.#ORG#.#DOMAIN#
        - orderer0.#ORG#.#DOMAIN#
        - ca.#ORG#.#DOMAIN#
      containers:     
      - name:  ccapi-#ORG#-#DOMAIN-FOR-LABEL#
        image:  node:carbon
        workingDir: /rest-server
        command: ["/bin/sh","-c"]        
        args: ["               
                [ ! -d 'node_modules' ] && npm install;\
                npm start; \
                sleep infinity"
              ]               
        env:
        - name: CONFIG_SDK_FILE
          value: configsdk-#ORG#.yaml
        - name: DOCKER
          value: "1"
        - name: CHANNEL
          value: mainchannel
        - name: CCNAME
          value: #CHAINCODE-NAME#          
        ports:
        - containerPort: PORT#
        volumeMounts:
          - mountPath: /certs
            subPath: orgs/#ORG#/certs            
            name: nfs-rest-server
          - mountPath: /rest-server
            subPath: orgs/#ORG#/rest-server            
            name: nfs-rest-server            
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: anyuid-root
      serviceAccountName: anyuid-root
      volumes:        
        - name: nfs-rest-server
          persistentVolumeClaim:
            claimName: pvc-cc-rest-server