kind: Service
apiVersion: v1
metadata:
  name: ssh-service
  namespace: hlpesproject-net
spec:
  selector:
    app: ssh-service  
  ports:  
    - name: ssh-port  
      port: 22
      protocol: TCP      
      targetPort: 22
  sessionAffinity: ClientIP